### ISSUE TITLE
How to start w/ Slate

### ISSUE THREAD

**Issue by hmaesta** [Elkfox/Concrete#81]
I am very sorry – and embarrassed – to create an issue this general. But... How to start, using Slate? 🤕

Documentation says:
```
$ git clone https://github.com/Elkfox/Concrete.git
$ cd Concrete
$ npm install
```

... but them command `slate deploy` doesn't work.

`yarn create slate-theme my-theme Elkfox/Concrete` doesn't work either.

Even if I manually download the .zip and include the `src` directory inside slate it doesn't work.

**Comment by cam** [comment]
@hmaesta no need to be embarrassed!

Are you using the [Slate v0 version](https://github.com/Elkfox/Concrete/tree/slate_0)? Or Slate v1 (master branch)?

Please note that we are currently creating a whole new version of Concrete that is designed to take full advantage of Slate v1 and NPM in order to create a much more seamless and progressive solution.

**Comment by hmaesta** [comment]
I am using Slate v1. That's probably why it doesn't work. 😅

**Comment by cam** [comment]
As long as you are using the Slate v1 branch, which is the master branch, you should be fine.

Have you been able to get Slate working on other builds on the same machine?

**Comment by cam** [comment]
New docs (WIP) are available at https://concrete.elkfox.io
